version: '3.4'

services:
  finance-db:
    image: postgres:15
    container_name: finance-db
    environment:
      - POSTGRES_DB=finance_db          
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=FIcartusettings 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: